# Generated by Django 2.0.13 on 2020-02-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200227_1250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderedproduct',
            unique_together={('product', 'order')},
        ),
    ]
