# Generated by Django 2.0.13 on 2020-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200227_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
